version: '3.7'
services:
  psycorp-frontend-dev:
    container_name: psycorp-frontend-dev
    build: ./
    volumes:
      - ../..:/app

  psycorp-nginx-dev:
    container_name: psycorp-nginx-dev
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../../:/app
    restart: always


